title: Puppies
modelClass: AzylAlfa\Dogbreeder\Models\Puppies
list: $/azylalfa/dogbreeder/models/puppies/columns.yaml
recordUrl: 'azylalfa/dogbreeder/puppies/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: published_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
