title: Categories
modelClass: AzylAlfa\Dogbreeder\Models\Category
list: $/azylalfa/dogbreeder/models/category/columns.yaml
recordUrl: 'azylalfa/dogbreeder/categories/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
